name: Weekly Release

on:
  schedule:
    - cron: "0 4 * * 0"
      branches:
        - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout master
        run: git checkout master
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install npm packages
        run: npm i
      - name: Publish monorepo packages
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          npx lerna publish --yes patch
